sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t gks/docker-react-app5 -f Dockerfile.dev ./

script: 
  - docker run -e CI=true gks/docker-react-app5 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-final
  env: Docker-react-final-env
  bucket_name: docker-react-app-bucket
  bucket_path: docker-react-final
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
