sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start Creating an image"
  - docker build -t gks/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true gks/docker-react-app npm run test -- --coverage

after_suceess:
  - echo "test success!!"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-3"
  env: "Docker-react-3-env"
  bucket_name: "elasticbeanstalk-us-east-2-383717135469"
  bucket_path: "docker-react-3"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY
  